### ISSUE TITLE
We couldn't connect to 'https://huggingface.co'

### ISSUE THREAD

**Issue by darrinh** [togethercomputer/OpenChatKit#129]
**Describe the bug**
when trying 'python3 inference/bot.py' , the follow error occurs:

```
Traceback (most recent call last):
  File "/home/darrin/miniconda3/envs/OpenChatKit/lib/python3.9/site-packages/transformers/configuration_utils.py", line 616, in _get_config_dict
    resolved_config_file = cached_path(
  File "/home/darrin/miniconda3/envs/OpenChatKit/lib/python3.9/site-packages/transformers/utils/hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "/home/darrin/miniconda3/envs/OpenChatKit/lib/python3.9/site-packages/transformers/utils/hub.py", line 562, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

the host is connected to the internet:

PING google.com (142.251.221.78) 56(84) bytes of data.
64 bytes from syd09s31-in-f14.1e100.net (142.251.221.78): icmp_seq=1 ttl=119 time=10.6 ms

PING huggingface.co (13.35.137.45) 56(84) bytes of data.
64 bytes from server-13-35-137-45.syd1.r.cloudfront.net (13.35.137.45): icmp_seq=1 ttl=242 time=11.8 ms
I can also curl https://huggingface.co from the host, any ideas of what its complaining about?

```

**Comment by orangetin** [comment]
Seems like a Transformers issue: https://github.com/huggingface/transformers/issues/11231

Not related to OpenChatKit
