### ISSUE TITLE
Exception in subprocess.py

### ISSUE THREAD

**Issue by jiandam55** [togethercomputer/OpenChatKit#43]
I run the following command:
python prepare.py

The result is as follows:

error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Traceback (most recent call last):
  File "prepare.py", line 18, in <module>
    process = subprocess.run(
  File "/root/miniconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git clone https://huggingface.co/datasets/laion/OIG /www/wwwroot/OpenChatKit/data/OIG/files' returned non-zero exit status 128.

Add:
curl https://huggingface.co/datasets/laion/OIG is OK.
And Permission is 777 in /www/wwwroot/OpenChatKit/data/OIG/files

Why?

**Comment by orangetin** [comment]
You seem to be talking about this file: ```data/OIG/prepare.py```

Please use the bug report template the next time. What OS are you running on?

It looks like this may be a problem with your internet, the TLS connection was terminated.

Can you run ```'git clone https://huggingface.co/datasets/laion/OIG /www/wwwroot/OpenChatKit/data/OIG/files``` in bash and see if that works? If it works, it may be a problem in Python. If not, it's most likely a problem with your internet connection. Try this out manually and report back with your results.

**Comment by csris** [comment]
Or it could also be your git configuration. Could you let me know if this command works (as @orangetin suggested)?

```
git clone https://huggingface.co/datasets/laion/OIG /www/wwwroot/OpenChatKit/data/OIG/files
```
