### ISSUE TITLE
Library not loaded: @rpath/libarchive.13.dyli on M2 Mac

### ISSUE THREAD

**Issue by Paninnet** [togethercomputer/OpenChatKit#96]
mamba env create -f environment.yml

Traceback (most recent call last):
File "/Users/ilya/anaconda3/bin/mamba", line 7, in
from mamba.mamba import main
File "/Users/ilya/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 49, in
import libmambapy as api
File "/Users/ilya/anaconda3/lib/python3.10/site-packages/libmambapy/init.py", line 7, in
raise e
File "/Users/ilya/anaconda3/lib/python3.10/site-packages/libmambapy/init.py", line 4, in
from libmambapy.bindings import * # noqa: F401,F403
ImportError: dlopen(/Users/ilya/anaconda3/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib

my conda-list

Name Version Build Channel
alabaster 0.7.12 pyhd3eb1b0_0
anaconda-client 1.11.1 py310hecd8cb5_0
anaconda-navigator 2.4.0 py310hecd8cb5_0
anaconda-project 0.11.1 py310hecd8cb5_0
anyio 3.5.0 py310hecd8cb5_0
appdirs 1.4.4 pyhd3eb1b0_0
applaunchservices 0.3.0 py310hecd8cb5_0
appnope 0.1.2 py310hecd8cb5_1001
appscript 1.1.2 py310hca72f7f_0
argon2-cffi 21.3.0 pyhd3eb1b0_0
argon2-cffi-bindings 21.2.0 py310hca72f7f_0
arrow 1.2.3 py310hecd8cb5_1
astroid 2.14.2 py310hecd8cb5_0
astropy 5.1 py310h4e76f89_0
asttokens 2.0.5 pyhd3eb1b0_0
atomicwrites 1.4.0 py_0
attrs 22.1.0 py310hecd8cb5_0
automat 20.2.0 py_0
autopep8 1.6.0 pyhd3eb1b0_1
babel 2.11.0 py310hecd8cb5_0
backcall 0.2.0 pyhd3eb1b0_0
backports 1.1 pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4 pyhd3eb1b0_0
backports.tempfile 1.0 pyhd3eb1b0_1
backports.weakref 1.0.post1 py_1
bcrypt 3.2.0 py310hca72f7f_1
beautifulsoup4 4.11.1 py310hecd8cb5_0
binaryornot 0.4.4 pyhd3eb1b0_1
black 22.6.0 py310hecd8cb5_0
blas 1.0 openblas
bleach 4.1.0 pyhd3eb1b0_0
blosc 1.21.3 hcec6c5f_0
bokeh 2.4.3 py310hecd8cb5_0
boltons 23.0.0 pyhd8ed1ab_0 conda-forge
bottleneck 1.3.5 py310h4e76f89_0
brotli 1.0.9 hca72f7f_7
brotli-bin 1.0.9 hca72f7f_7
brotlipy 0.7.0 py310hca72f7f_1002
brunsli 0.1 h23ab428_0
bzip2 1.0.8 h1de35cc_0
c-ares 1.18.1 hca72f7f_0
ca-certificates 2022.12.7 h033912b_0 conda-forge
cctools 949.0.1 h9abeeb2_25
cctools_osx-64 949.0.1 hc7db93f_25
certifi 2022.12.7 pyhd8ed1ab_0 conda-forge
cffi 1.15.1 py310h6c40b1e_3
cfitsio 3.470 hbd21bf8_7
chardet 4.0.0 py310hecd8cb5_1003
charls 2.2.0 h23ab428_0
charset-normalizer 2.0.4 pyhd3eb1b0_0
click 8.0.4 py310hecd8cb5_0
cloudpickle 2.0.0 pyhd3eb1b0_0
clyent 1.2.2 py310hecd8cb5_1
colorama 0.4.6 py310hecd8cb5_0
colorcet 3.0.1 py310hecd8cb5_0
comm 0.1.2 py310hecd8cb5_0
conda 23.3.1 py310hecd8cb5_0
conda-build 3.23.3 py310hecd8cb5_0
conda-content-trust 0.1.3 py310hecd8cb5_0
conda-pack 0.6.0 pyhd3eb1b0_0
conda-package-handling 2.0.2 py310hecd8cb5_0
conda-package-streaming 0.7.0 py310hecd8cb5_0
conda-repo-cli 1.0.27 py310hecd8cb5_0
conda-token 0.4.0 pyhd3eb1b0_0
conda-verify 3.4.2 py_1
constantly 15.1.0 py310hecd8cb5_0
contourpy 1.0.5 py310haf03e11_0
cookiecutter 1.7.3 pyhd3eb1b0_0
cryptography 39.0.1 py310hf6deb26_0
cssselect 1.1.0 pyhd3eb1b0_0
cycler 0.11.0 pyhd3eb1b0_0
cytoolz 0.12.0 py310hca72f7f_0
dask 2022.7.0 py310hecd8cb5_0
dask-core 2022.7.0 py310hecd8cb5_0
datashader 0.14.4 py310hecd8cb5_0
datashape 0.5.4 py310hecd8cb5_1
debugpy 1.5.1 py310he9d5cce_0
decorator 5.1.1 pyhd3eb1b0_0
defusedxml 0.7.1 pyhd3eb1b0_0
diff-match-patch 20200713 pyhd3eb1b0_0
dill 0.3.6 py310hecd8cb5_0
distributed 2022.7.0 py310hecd8cb5_0
docstring-to-markdown 0.11 py310hecd8cb5_0
docutils 0.18.1 py310hecd8cb5_3
entrypoints 0.4 py310hecd8cb5_0
et_xmlfile 1.1.0 py310hecd8cb5_0
executing 0.8.3 pyhd3eb1b0_0
filelock 3.9.0 py310hecd8cb5_0
flake8 6.0.0 py310hecd8cb5_0
flask 2.2.2 py310hecd8cb5_0
flit-core 3.6.0 pyhd3eb1b0_0
fmt 9.1.0 hb8565cd_0 conda-forge
fonttools 4.25.0 pyhd3eb1b0_0
freetype 2.12.1 hd8bbffd_0
fsspec 2022.11.0 py310hecd8cb5_0
future 0.18.3 py310hecd8cb5_0
gensim 4.3.0 py310h3ea8b11_0
gettext 0.21.1 h8a4c099_0 conda-forge
giflib 5.2.1 h6c40b1e_3
glib 2.76.1 hbc0c0cd_0 conda-forge
glib-tools 2.76.1 hbc0c0cd_0 conda-forge
glob2 0.7 pyhd3eb1b0_0
gmp 6.2.1 he9d5cce_3
gmpy2 2.1.2 py310hd5de756_0
greenlet 2.0.1 py310hcec6c5f_0
gst-plugins-base 1.22.0 h37e1711_2 conda-forge
gstreamer 1.22.0 h1d18e73_2 conda-forge
h5py 3.7.0 py310h6c517f8_0
hdf5 1.10.6 h10fe05b_1
heapdict 1.0.1 pyhd3eb1b0_0
holoviews 1.15.4 py310hecd8cb5_0
huggingface_hub 0.10.1 py310hecd8cb5_0
hvplot 0.8.2 py310hecd8cb5_0
hyperlink 21.0.0 pyhd3eb1b0_0
icu 70.1 h96cf925_0 conda-forge
idna 3.4 py310hecd8cb5_0
imagecodecs 2021.8.26 py310hf5cf8d7_2
imageio 2.26.0 py310hecd8cb5_0
imagesize 1.4.1 py310hecd8cb5_0
imbalanced-learn 0.10.1 py310hecd8cb5_0
importlib-metadata 4.11.3 py310hecd8cb5_0
importlib_metadata 4.11.3 hd3eb1b0_0
incremental 21.3.0 pyhd3eb1b0_0
inflection 0.5.1 py310hecd8cb5_0
iniconfig 1.1.1 pyhd3eb1b0_0
intake 0.6.7 py310hecd8cb5_0
intervaltree 3.1.0 pyhd3eb1b0_0
ipykernel 6.19.2 py310h20db666_0
ipython 8.10.0 py310hecd8cb5_0
ipython_genutils 0.2.0 pyhd3eb1b0_1
ipywidgets 7.6.5 pyhd3eb1b0_1
isort 5.9.3 pyhd3eb1b0_0
itemadapter 0.3.0 pyhd3eb1b0_0
itemloaders 1.0.4 pyhd3eb1b0_1
itsdangerous 2.0.1 pyhd3eb1b0_0
jedi 0.18.1 py310hecd8cb5_1
jellyfish 0.9.0 py310hca72f7f_0
jinja2 3.1.2 py310hecd8cb5_0
jinja2-time 0.2.0 pyhd3eb1b0_3
jmespath 0.10.0 pyhd3eb1b0_0
joblib 1.1.1 py310hecd8cb5_0
jpeg 9e h6c40b1e_1
jq 1.6 h9ed2024_1000
json5 0.9.6 pyhd3eb1b0_0
jsonpatch 1.32 pyhd8ed1ab_0 conda-forge
jsonpointer 2.0 py_0 conda-forge
jsonschema 4.17.3 py310hecd8cb5_0
jupyter 1.0.0 py310hecd8cb5_8
jupyter_client 7.3.4 py310hecd8cb5_0
jupyter_console 6.6.2 py310hecd8cb5_0
jupyter_core 5.2.0 py310hecd8cb5_0
jupyter_server 1.23.4 py310hecd8cb5_0
jupyterlab 3.5.3 py310hecd8cb5_0
jupyterlab_pygments 0.1.2 py_0
jupyterlab_server 2.19.0 py310hecd8cb5_0
jupyterlab_widgets 1.0.0 pyhd3eb1b0_1
jxrlib 1.1 haf1e3a3_2
keyring 23.4.0 py310hecd8cb5_0
kiwisolver 1.4.4 py310hcec6c5f_0
krb5 1.20.1 h049b76e_0 conda-forge
lazy-object-proxy 1.6.0 py310hca72f7f_0
lcms2 2.12 hf1fd2bf_0
ld64 530 h20443b4_25
ld64_osx-64 530 h70f3046_25
ldid 2.1.2 h2d21305_2
lerc 3.0 he9d5cce_0
libaec 1.0.4 hb1e8313_1
libarchive 3.6.2 h65c5294_0
libbrotlicommon 1.0.9 hca72f7f_7
libbrotlidec 1.0.9 hca72f7f_7
libbrotlienc 1.0.9 hca72f7f_7
libclang 13.0.1 default_he082bbe_0 conda-forge
libcurl 7.88.1 h6df9250_1 conda-forge
libcxx 14.0.6 h9765a3e_0
libdeflate 1.17 hb664fd8_0
libedit 3.1.20221030 h6c40b1e_0
libev 4.33 h9ed2024_1
libffi 3.4.2 hecd8cb5_6
libgfortran 5.0.0 11_3_0_hecd8cb5_28
libgfortran5 11.3.0 h9dfd629_28
libglib 2.76.1 h4c723e1_0 conda-forge
libiconv 1.17 hac89ed1_0 conda-forge
liblief 0.12.3 hcec6c5f_0
libllvm11 11.1.0 h46f1229_6
libllvm12 12.0.0 h9b2ccf5_3
libllvm13 13.0.1 h64f94b2_2 conda-forge
libllvm14 14.0.6 h91fad77_1
libmamba 1.4.2 h9d281b0_0 conda-forge
libmambapy 1.4.2 py310hb15139c_0 conda-forge
libnghttp2 1.52.0 he2ab024_0 conda-forge
libogg 1.3.4 h35c211d_1 conda-forge
libopenblas 0.3.21 h54e7dc3_0
libopus 1.3.1 hc929b4f_1 conda-forge
libpng 1.6.39 h6c40b1e_0
libpq 15.2 h3640bf0_0 conda-forge
libprotobuf 3.20.3 hfff2838_0
libsodium 1.0.18 h1de35cc_0
libsolv 0.7.23 hbc0c0cd_0 conda-forge
libspatialindex 1.9.3 h23ab428_0
libsqlite 3.40.0 ha978bb4_0 conda-forge
libssh2 1.10.0 h47af595_3 conda-forge
libtiff 4.5.0 hcec6c5f_2
libuv 1.44.2 h6c40b1e_0
libvorbis 1.3.7 h046ec9c_0 conda-forge
libwebp 1.2.4 hf6ce154_1
libwebp-base 1.2.4 h6c40b1e_1
libxml2 2.9.14 hea49891_4 conda-forge
libxslt 1.1.35 h5b33f42_0
libzlib 1.2.13 hfd90126_4 conda-forge
libzopfli 1.0.3 hb1e8313_0
llvm-openmp 14.0.6 h0dcd299_0
llvmlite 0.39.1 py310h8346a28_0
locket 1.0.0 py310hecd8cb5_0
lxml 4.9.1 py310h65b224f_0
lz4 3.1.3 py310hca72f7f_0
lz4-c 1.9.4 hcec6c5f_0
lzo 2.10 haf1e3a3_2
mamba 1.4.2 py310h6bde348_0 conda-forge
markdown 3.4.1 py310hecd8cb5_0
markupsafe 2.1.1 py310hca72f7f_0
matplotlib 3.7.0 py310hecd8cb5_0
matplotlib-base 3.7.0 py310ha533b9c_0
matplotlib-inline 0.1.6 py310hecd8cb5_0
mccabe 0.7.0 pyhd3eb1b0_0
mistune 0.8.4 py310hca72f7f_1000
mock 4.0.3 pyhd3eb1b0_0
mpc 1.1.0 h6ef4df4_1
mpfr 4.0.2 h9066e36_1
mpmath 1.2.1 pypi_0 pypi
msgpack-python 1.0.3 py310haf03e11_0
multipledispatch 0.6.0 py310hecd8cb5_0
munkres 1.1.4 py_0
mypy_extensions 0.4.3 py310hecd8cb5_1
mysql-common 8.0.32 hc4b2c72_1 conda-forge
mysql-libs 8.0.32 h8658499_1 conda-forge
navigator-updater 0.3.0 py310hecd8cb5_0
nbclassic 0.5.2 py310hecd8cb5_0
nbclient 0.5.13 py310hecd8cb5_0
nbconvert 6.5.4 py310hecd8cb5_0
nbformat 5.7.0 py310hecd8cb5_0
ncurses 6.4 hcec6c5f_0
nest-asyncio 1.5.6 py310hecd8cb5_0
networkx 2.8.4 py310hecd8cb5_0
ninja 1.10.2 hecd8cb5_5
ninja-base 1.10.2 haf03e11_5
nltk 3.7 pyhd3eb1b0_0
notebook 6.5.2 py310hecd8cb5_0
notebook-shim 0.2.2 py310hecd8cb5_0
nspr 4.35 hea0b92c_0 conda-forge
nss 3.89 h78b00b3_0 conda-forge
numba 0.56.4 py310h3ea8b11_0
numexpr 2.8.4 py310he50c29a_0
numpy 1.23.5 py310he50c29a_0
numpy-base 1.23.5 py310h992e150_0
numpydoc 1.5.0 py310hecd8cb5_0
oniguruma 6.9.7.1 h9ed2024_0
openjpeg 2.4.0 h66ea3da_0
openpyxl 3.0.10 py310hca72f7f_0
openssl 3.1.0 hfd90126_0 conda-forge
packaging 22.0 py310hecd8cb5_0
pandas 1.5.3 py310h3ea8b11_0
pandocfilters 1.5.0 pyhd3eb1b0_0
panel 0.14.3 py310hecd8cb5_0
param 1.12.3 py310hecd8cb5_0
parsel 1.6.0 py310hecd8cb5_0
parso 0.8.3 pyhd3eb1b0_0
partd 1.2.0 pyhd3eb1b0_1
patch 2.7.6 h1de35cc_1001
pathlib 1.0.1 pyhd3eb1b0_1
pathspec 0.10.3 py310hecd8cb5_0
patsy 0.5.3 py310hecd8cb5_0
pcre 8.45 h23ab428_0
pcre2 10.40 h1c4e4bc_0 conda-forge
pep8 1.7.1 py310hecd8cb5_1
pexpect 4.8.0 pyhd3eb1b0_3
pickleshare 0.7.5 pyhd3eb1b0_1003
pillow 9.4.0 py310hcec6c5f_0
pip 22.3.1 py310hecd8cb5_0
pkginfo 1.8.3 py310hecd8cb5_0
platformdirs 2.5.2 py310hecd8cb5_0
plotly 5.9.0 py310hecd8cb5_0
pluggy 1.0.0 py310hecd8cb5_1
ply 3.11 py310hecd8cb5_0
pooch 1.4.0 pyhd3eb1b0_0
poyo 0.5.0 pyhd3eb1b0_0
prometheus_client 0.14.1 py310hecd8cb5_0
prompt-toolkit 3.0.36 py310hecd8cb5_0
prompt_toolkit 3.0.36 hd3eb1b0_0
protego 0.1.16 py_0
psutil 5.9.0 py310hca72f7f_0
ptyprocess 0.7.0 pyhd3eb1b0_2
pure_eval 0.2.2 pyhd3eb1b0_0
py 1.11.0 pyhd3eb1b0_0
py-lief 0.12.3 py310hcec6c5f_0
pyasn1 0.4.8 pyhd3eb1b0_0
pyasn1-modules 0.2.8 py_0
pybind11-abi 4 hd8ed1ab_3 conda-forge
pycodestyle 2.10.0 py310hecd8cb5_0
pycosat 0.6.4 py310hca72f7f_0
pycparser 2.21 pyhd3eb1b0_0
pyct 0.5.0 py310hecd8cb5_0
pydispatcher 2.0.5 py310hecd8cb5_2
pydocstyle 6.3.0 py310hecd8cb5_0
pyerfa 2.0.0 py310hca72f7f_0
pyflakes 3.0.1 py310hecd8cb5_0
pygments 2.11.2 pyhd3eb1b0_0
pyhamcrest 2.0.2 pyhd3eb1b0_2
pyjwt 2.4.0 py310hecd8cb5_0
pylint 2.16.2 py310hecd8cb5_0
pylint-venv 2.3.0 py310hecd8cb5_0
pyls-spyder 0.4.0 pyhd3eb1b0_0
pyobjc-core 9.0 py310h9205ec4_1
pyobjc-framework-cocoa 9.0 py310h9205ec4_0
pyobjc-framework-coreservices 9.0 py310h46256e1_0
pyobjc-framework-fsevents 9.0 py310hecd8cb5_0
pyodbc 4.0.34 py310he9d5cce_0
pyopenssl 23.0.0 py310hecd8cb5_0
pyparsing 3.0.9 py310hecd8cb5_0
pyqt 5.15.7 py310he9d5cce_0
pyqt5-sip 12.11.0 pypi_0 pypi
pyqtwebengine 5.15.7 py310he9d5cce_0
pyrsistent 0.18.0 py310hca72f7f_0
pysocks 1.7.1 py310hecd8cb5_0
pytables 3.7.0 py310h59775c6_1
pytest 7.1.2 py310hecd8cb5_0
python 3.10.10 he7542f4_0_cpython conda-forge
python-dateutil 2.8.2 pyhd3eb1b0_0
python-fastjsonschema 2.16.2 py310hecd8cb5_0
python-libarchive-c 2.9 pyhd3eb1b0_1
python-lsp-black 1.2.1 py310hecd8cb5_0
python-lsp-jsonrpc 1.0.0 pyhd3eb1b0_0
python-lsp-server 1.7.1 py310hecd8cb5_0
python-slugify 5.0.2 pyhd3eb1b0_0
python-snappy 0.6.1 py310hcec6c5f_0
python.app 3 py310hca72f7f_0
python_abi 3.10 3_cp310 conda-forge
pytoolconfig 1.2.5 py310hecd8cb5_1
pytorch 1.12.1 cpu_py310h64f2f56_1
pytz 2022.7 py310hecd8cb5_0
pyviz_comms 2.0.2 pyhd3eb1b0_0
pywavelets 1.4.1 py310h6c40b1e_0
pyyaml 6.0 py310h6c40b1e_1
pyzmq 23.2.0 py310he9d5cce_0
qdarkstyle 3.0.2 pyhd3eb1b0_0
qstylizer 0.2.2 py310hecd8cb5_0
qt-main 5.15.8 h1d3b3f8_6 conda-forge
qt-webengine 5.15.9 h90a370e_4
qtawesome 1.2.2 py310hecd8cb5_0
qtconsole 5.4.0 py310hecd8cb5_0
qtpy 2.2.0 py310hecd8cb5_0
qtwebkit 5.212 ha2e9019_6 conda-forge
queuelib 1.5.0 py310hecd8cb5_0
readline 8.2 hca72f7f_0
regex 2022.7.9 py310hca72f7f_0
reproc 14.2.4 hb7f2c08_0 conda-forge
reproc-cpp 14.2.4 hf0c8a7f_0 conda-forge
requests 2.28.1 py310hecd8cb5_0
requests-file 1.5.1 pyhd3eb1b0_0
ripgrep 13.0.0 hc2228c6_0
rope 1.7.0 py310hecd8cb5_0
rtree 1.0.1 py310hecd8cb5_0
ruamel.yaml 0.17.21 py310hca72f7f_0
ruamel.yaml.clib 0.2.6 py310hca72f7f_1
ruamel_yaml 0.17.21 py310hca72f7f_0
scikit-image 0.19.3 py310hcec6c5f_1
scikit-learn 1.2.1 py310hcec6c5f_0
scipy 1.10.0 py310ha516a68_1
scrapy 2.8.0 py310hecd8cb5_0
seaborn 0.12.2 py310hecd8cb5_0
send2trash 1.8.0 pyhd3eb1b0_1
service_identity 18.1.0 pyhd3eb1b0_1
setuptools 65.6.3 py310hecd8cb5_0
sip 6.6.2 py310he9d5cce_0
six 1.16.0 pyhd3eb1b0_1
smart_open 5.2.1 py310hecd8cb5_0
snappy 1.1.9 he9d5cce_0
sniffio 1.2.0 py310hecd8cb5_1
snowballstemmer 2.2.0 pyhd3eb1b0_0
sortedcontainers 2.4.0 pyhd3eb1b0_0
soupsieve 2.3.2.post1 py310hecd8cb5_0
sphinx 5.0.2 py310hecd8cb5_0
sphinxcontrib-applehelp 1.0.2 pyhd3eb1b0_0
sphinxcontrib-devhelp 1.0.2 pyhd3eb1b0_0
sphinxcontrib-htmlhelp 2.0.0 pyhd3eb1b0_0
sphinxcontrib-jsmath 1.0.1 pyhd3eb1b0_0
sphinxcontrib-qthelp 1.0.3 pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5 pyhd3eb1b0_0
spyder 5.4.1 py310hecd8cb5_0
spyder-kernels 2.4.1 py310hecd8cb5_0
sqlalchemy 1.4.39 py310hca72f7f_0
sqlite 3.40.1 h880c91c_0
stack_data 0.2.0 pyhd3eb1b0_0
statsmodels 0.13.5 py310h7b7cdfe_1
sympy 1.11.1 py310hecd8cb5_0
tabulate 0.8.10 py310hecd8cb5_0
tapi 1000.10.8 ha1b3eb9_0
tbb 2021.7.0 ha357a0b_0
tbb4py 2021.7.0 py310ha357a0b_0
tblib 1.7.0 pyhd3eb1b0_0
tenacity 8.0.1 py310hecd8cb5_1
terminado 0.17.1 py310hecd8cb5_0
text-unidecode 1.3 pyhd3eb1b0_0
textdistance 4.2.1 pyhd3eb1b0_0
threadpoolctl 2.2.0 pyh0d69192_0
three-merge 0.1.1 pyhd3eb1b0_0
tifffile 2021.7.2 pyhd3eb1b0_2
tinycss2 1.2.1 py310hecd8cb5_0
tk 8.6.12 h5d9f67b_0
tldextract 3.2.0 pyhd3eb1b0_0
tokenizers 0.11.4 py310h8776b5c_1
toml 0.10.2 pyhd3eb1b0_0
tomli 2.0.1 py310hecd8cb5_0
tomlkit 0.11.1 py310hecd8cb5_0
toolz 0.12.0 py310hecd8cb5_0
tornado 6.1 py310hca72f7f_0
tqdm 4.64.1 py310hecd8cb5_0
traitlets 5.7.1 py310hecd8cb5_0
transformers 4.24.0 py310hecd8cb5_0
twisted 22.2.0 py310hca72f7f_1
typing-extensions 4.4.0 py310hecd8cb5_0
typing_extensions 4.4.0 py310hecd8cb5_0
tzdata 2022g h04d1e81_0
ujson 5.4.0 py310he9d5cce_0
unidecode 1.2.0 pyhd3eb1b0_0
unixodbc 2.3.11 hb456775_0
urllib3 1.26.14 py310hecd8cb5_0
w3lib 1.21.0 pyhd3eb1b0_0
watchdog 2.1.6 py310h999c104_0
wcwidth 0.2.5 pyhd3eb1b0_0
webencodings 0.5.1 py310hecd8cb5_1
websocket-client 0.58.0 py310hecd8cb5_4
werkzeug 2.2.2 py310hecd8cb5_0
whatthepatch 1.0.2 py310hecd8cb5_0
wheel 0.38.4 py310hecd8cb5_0
widgetsnbextension 3.5.2 py310hecd8cb5_0
wrapt 1.14.1 py310hca72f7f_0
wurlitzer 3.0.2 py310hecd8cb5_0
xarray 2022.11.0 py310hecd8cb5_0
xlwings 0.29.1 py310hecd8cb5_0
xz 5.2.10 h6c40b1e_1
yaml 0.2.5 haf1e3a3_0
yaml-cpp 0.7.0 hf0c8a7f_2 conda-forge
yapf 0.31.0 pyhd3eb1b0_0
zeromq 4.3.4 h23ab428_0
zfp 0.5.5 he9d5cce_6
zict 2.1.0 py310hecd8cb5_0
zipp 3.11.0 py310hecd8cb5_0
zlib 1.2.13 hfd90126_4 conda-forge
zope 1.0 py310hecd8cb5_1
zope.interface 5.4.0 py310hca72f7f_0
zstandard 0.19.0 py310h6c40b1e_0
zstd 1.5.2 hcb37349_0
(base) ilya@MacBook-Air-Ilya ~ %

@Paninnet

 
Add heading textAdd bold text, <Cmd+b>Add italic text, <Cmd+i>
Add a quote, <Cmd+Shift+.>Add code, <Cmd+e>Add a link, <Cmd+k>
Add a bulleted list, <Cmd+Shift+8>Add a numbered list, <Cmd+Shift+7>Add a task list, <Cmd+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Slash commands
Leave a comment
Файл не выбран
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/mamba-org/mamba/blob/395095f7879fd83cd6ac8e1090a39d0bdd612f6c/CONTRIBUTING.md) and [security policy](https://github.com/mamba-org/mamba/blob/395095f7879fd83cd6ac8e1090a39d0bdd612f6c/SECURITY.md).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you authored the thread.
1 participant
@Paninnet
Footer
© 2023 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
[Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
[Security](https://github.com/security)

**Comment by orangetin** [comment]
This is a known issue with Mamba on Mac. Refer to this open issue:
- mamba-org/mamba#1826

Also, refer to this closed issue that could help you:
- mamba-org/mamba#1897

I see that you have opened an issue in the mamba repo, so this can be closed as it is not an issue with OCK.

**Comment by mwunderlich** [comment]
For anyone else that might come across this issue while trying to install the conda enviroment for OpenChatKit, the following solution worked for me (on M1 Macbook pro): 
```
brew install libarchive
ln -s /usr/local/opt/libarchive/lib/libarchive.13.dylib /usr/local/lib/
```
(this solution was mentioned in the issue comments of the mamba repo)
